AWSTemplateFormatVersion: "2010-09-09"

Description: >-
                Key Pair for EC2 instances

Parameters:
  KeyName:
    Description: The name of the key pair
    Type: String
    Default: group03-keypair

Resources:
  KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: !Ref KeyName
      KeyType: rsa
      KeyFormat: pem
      Tags:
        - Key: Application
          Value: !Ref AWS::StackName
        - Key: Name
          Value: !Ref KeyName

Outputs:
  KeyName:
    Description: The name of the EC2 KeyPair
    Value: !Ref KeyPair
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-KeyName