AWSTemplateFormatVersion: "2010-09-09"

Description: >-
  EIP: Specifies an Elastic IP (EIP) address and can, optionally, associate it with an Amazon EC2 instance.

Parameters:
  VpcId:
    Description: The ID of the VPC
    Type: String
  VpcName:
    Description: The name of the VPC
    Type: String
  PublicSubnet1:
    Description: The ID of the Public Subnet 1
    Type: String
  PublicSubnet2:
    Description: The ID of the Public Subnet 2
    Type: String

Resources:
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Application
          Value: !Ref AWS::StackName
        - Key: Network
          Value: Public
        - Key: Name
          Value: !Join 
            - "-"
            - - !Ref VpcName
              - igw

  GatewayToInternet:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VpcId
      InternetGatewayId: !Ref InternetGateway

  ElasticIP1:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc # The network (vpc).

  ElasticIP2:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc # The network (vpc).

  NATGateway1:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt ElasticIP1.AllocationId
      SubnetId: !Ref PublicSubnet1

  NATGateway2:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt ElasticIP2.AllocationId
      SubnetId: !Ref PublicSubnet2

Outputs:
  NATGateway1:
    Description: The ID of the NAT Gateway 1
    Value: !Ref NATGateway1
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-NATGateway1

  NATGateway2:
    Description: The ID of the NAT Gateway 2
    Value: !Ref NATGateway2
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-NATGateway2

  InternetGateway:
    Description: The ID of the Internet Gateway
    Value: !Ref InternetGateway
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-InternetGateway

  ElasticIP1:
    Description: The ID of the Elastic IP 1
    Value: !Ref ElasticIP1
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-ElasticIP1

  ElasticIP2:
    Description: The ID of the Elastic IP 2
    Value: !Ref ElasticIP2
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-ElasticIP2